dev/user - user crud operations
fedran/dreamblog pull request #2
Opened 2021-01-03 09:31 UTC by fedran

2021-01-03 09:32 UTC, fedran commented on sources/src/main/java/org/zhuch/dreamblog/domain/Role.java
> +    @NotNull
зачем аннотация NotNull если я и так возвращаю не null?

2021-01-03 10:11 UTC, zhuch-iv commented on sources/src/main/java/org/zhuch/dreamblog/domain/Role.java
> +    @NotNull
для того что бы сказать в сигнатуре метода что ты не налл возвращаешь =)

2021-01-03 10:39 UTC, zhuch-iv requested changes

2021-01-03 10:39 UTC, zhuch-iv commented on sources/src/main/java/org/zhuch/dreamblog/domain/Role.java
> +    public static Role fromInt(final int i) {
это переписать

2021-01-03 10:39 UTC, zhuch-iv commented on sources/src/main/java/org/zhuch/dreamblog/domain/Role.java
> +    public static int toInt(@NotNull final Role role) {
`return role.value`

2021-01-03 10:39 UTC, zhuch-iv commented on sources/src/main/java/org/zhuch/dreamblog/domain/Role.java
> +    ADMIN, USER;
`ADMIN(1), USER(2);` ...

2021-01-03 10:39 UTC, zhuch-iv commented on sources/src/main/java/org/zhuch/dreamblog/domain/service/UserService.java
> +
`private final PasswordEncoder passwordEncoder;`

в конфигурацию -
```java

@Bean
public PasswordEncoder passwordEncoder() {
    return new BCryptPasswordEncoder();
}
```

2021-01-03 10:39 UTC, zhuch-iv commented on sources/src/main/java/org/zhuch/dreamblog/domain/User.java
> +    public static User fromDto(final UserDto userDto) {
Метод с хешированием пароля - не статический, в юзер сервисе

2021-01-03 10:39 UTC, zhuch-iv commented on sources/src/main/java/org/zhuch/dreamblog/input/controller/UserController.java
> +            @RequestParam(name = "size", required = false) final Integer size) {
```java
    @GetMapping(produces = MediaType.APPLICATION_JSON_VALUE)
    public List<UserDto> getUsers(
            @RequestParam(name = "pattern", required = false) final String pattern,
            @RequestParam(name = "page", required = false) final Integer page,
            @RequestParam(name = "size", required = false) final Integer size
    ) {
```

2021-01-03 10:39 UTC, zhuch-iv commented on sources/src/main/java/org/zhuch/dreamblog/domain/service/UserService.java
> +                           @Nullable Integer size) {
```java
    public List<User> find(
        @Nullable final String pattern,
        @Nullable Integer page,
        @Nullable Integer size
    ) {
```

2021-01-03 11:00 UTC, fedran commented on sources/src/main/java/org/zhuch/dreamblog/domain/Role.java
> +    public static Role fromInt(final int i) {
swith case 
default: throw new IllegalArgument

2021-01-03 11:04 UTC, fedran commented on sources/src/main/java/org/zhuch/dreamblog/domain/service/UserService.java
> +
создать конфигурацию 
@Configuration
SecurityConfiguration

2021-01-03 11:08 UTC, fedran commented on sources/src/main/java/org/zhuch/dreamblog/domain/User.java
> +    public static User fromDto(final UserDto userDto) {
создать UserAssembler 
превращает UserDto в User

2021-01-03 11:13 UTC, fedran commented
проставить аннотации @Autowired над всеми конструкторами бонов спринта

2021-01-05 12:26 UTC, zhuch-iv requested changes

2021-01-05 12:26 UTC, zhuch-iv commented on pom.xml
> +            <groupId>org.springframework.security</groupId>
Не в общий помник, а в помник модуля

2021-01-05 12:26 UTC, zhuch-iv commented on sources/pom.xml
> +    <artifactId>sources</artifactId>
Тут все так и задуманно верни обратно

2021-01-05 12:26 UTC, zhuch-iv commented on sources/pom.xml
> -    <java.version>11</java.version>
Верни

2021-01-05 12:26 UTC, zhuch-iv commented on sources/src/main/java/org/zhuch/dreamblog/DreamblogApplication.java
> +@EnableJdbcAuditing
Лесенкой от меньшего к большему, не переставляй пожалуйста

2021-01-05 12:26 UTC, zhuch-iv commented on sources/src/main/java/org/zhuch/dreamblog/domain/Role.java
> +    int ordinalNumber;
`private int id`

2021-01-05 12:26 UTC, zhuch-iv commented on sources/src/main/java/org/zhuch/dreamblog/domain/User.java
> +    }
`Role.toInt`

2021-01-05 12:26 UTC, zhuch-iv commented on sources/src/main/java/org/zhuch/dreamblog/domain/service/UserService.java
> +        final UserRow saveParamsRow = user.toRow();
Ужасные названия переменных, можно и без переменных обойтись

2021-01-05 12:36 UTC, fedran commented on sources/pom.xml
> +    <artifactId>sources</artifactId>
о чем речь?

2021-01-05 12:36 UTC, fedran commented on sources/pom.xml
> -    <java.version>11</java.version>
о чем речь?

2021-01-05 12:51 UTC, merged