dev/article - article model updated
fedran/dreamblog pull request #3
Opened 2021-01-05 12:55 UTC by fedran

Caption, likes, dislikes, views added to article model.

2021-01-05 14:20 UTC, zhuch-iv commented on database/src/main/resources/database/0.1.0/02_article_table.sql
> +    likes int,
bigint not null default 0

2021-01-05 14:20 UTC, zhuch-iv commented on database/src/main/resources/database/0.1.0/02_article_table.sql
> +    views int
bigint not null default 0

2021-01-05 14:20 UTC, zhuch-iv commented on database/src/main/resources/database/0.1.0/02_article_table.sql
> +    dislikes int,
bigint not null default 0

2021-01-05 14:20 UTC, zhuch-iv commented on sources/src/main/java/org/zhuch/dreamblog/domain/Article.java
> +    int likes;
То же самое

2021-01-05 14:20 UTC, zhuch-iv commented on sources/src/main/java/org/zhuch/dreamblog/persistence/row/ArticleRow.java
> +        final Long userId, final String caption, final String content,
Лучше без final

2021-01-05 14:20 UTC, zhuch-iv commented on sources/src/main/java/org/zhuch/dreamblog/persistence/repository/IArticleCommentsRepository.java
>      @Query(
Неплохо было бы отдельные методы в ArticleRepository, на обновление лайков, дизов и просмотров

2021-01-05 14:29 UTC, fedran commented on sources/src/main/java/org/zhuch/dreamblog/persistence/repository/IArticleCommentsRepository.java
>      @Query(
ридонли проперти над лайками, дизами и просмотрами в Row;
в репозитории с артиклами:
@Query(select текущий лайк  и + 1 к текущему лайку)
inceremtsLike

2021-01-06 09:52 UTC, fedran commented on sources/src/main/java/org/zhuch/dreamblog/domain/Article.java
> +    int likes;
о чем речь?

2021-01-06 09:53 UTC, fedran commented on sources/src/main/java/org/zhuch/dreamblog/persistence/row/ArticleRow.java
> +        final Long userId, final String caption, final String content,
поч?

2021-01-06 12:03 UTC, zhuch-iv requested changes

2021-01-06 12:03 UTC, zhuch-iv commented on sources/src/main/java/org/zhuch/dreamblog/domain/service/ArticleService.java
> +        article.withCreated(LocalDateTime.now());
Сущность иммутабельная

2021-01-06 12:03 UTC, zhuch-iv commented on sources/src/main/java/org/zhuch/dreamblog/domain/service/ArticleService.java
> +        final Page<ArticleRow> arPage = articleRepository.findAll(PageRequest.of(page, size));
Не вижу смысла в создании переменных на пустом месте ещё и с плохими названиями

2021-01-06 12:03 UTC, zhuch-iv commented on sources/src/main/java/org/zhuch/dreamblog/domain/service/UserService.java
> +        user.withCreated(LocalDateTime.now());
То же самое

2021-01-06 12:03 UTC, zhuch-iv commented on sources/src/main/java/org/zhuch/dreamblog/persistence/repository/IArticleRepository.java
> +            "( SELECT user_id FROM " + USER +
Чёт форматирование

2021-01-06 12:03 UTC, zhuch-iv commented on database/src/main/resources/database/0.1.0/02_articles_table.sql
> +    likes bigint NOT NULL DEFAULT 0,
Лучше без s

2021-01-06 12:34 UTC, merged

2021-01-06 12:35 UTC, fedran commented on sources/src/main/java/org/zhuch/dreamblog/persistence/repository/IArticleRepository.java
> +            "( SELECT user_id FROM " + USER +
как надо?

2021-01-06 12:36 UTC, fedran commented on database/src/main/resources/database/0.1.0/02_articles_table.sql
> +    likes bigint NOT NULL DEFAULT 0,
без s он не понимает, как прописать правильно?